### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ndsvw** [ndsvw/STARTPAGE#1]
# TODO
### Priority:
- [ ] Create a good readme.md
- [ ] administrate box clicks (show, how many clicks | more clicks -> less box transparency)
- [x] improve color boxes, fix existing bugs
- [x] include a better possibility to pick the color
### Maybe:
- [ ] improve the bottom link list (other style)

**Comment by ndsvw** [comment]
- [x] bugfix (boxes appear several times if text gets written in searchbox)
